os: linux
dist: xenial
language: php

php:
  - "8.1"
  - "8.2"

jobs:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # disable xdebug if available
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer validate
  - composer global require hirak/prestissimo
  # Copy required files.
  - cp phpcs.dist.xml phpcs.xml
  - cp phpunit.dist.xml phpunit.xml
  - cp grumphp.dist.yml grumphp.yml

install:
  - composer install --no-suggest --no-progress --no-interaction --prefer-dist -o

script:
  - vendor/bin/parallel-lint test
  - vendor/bin/phpcs --standard=phpcs.xml test
  - vendor/bin/parallel-lint src
  - vendor/bin/phpcs --standard=phpcs.xml src
  - vendor/bin/phpunit -c phpunit.xml
  - vendor/bin/phpstan analyze src
  - vendor/bin/phpstan analyze test
